apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      chapter: sdev372
  template:
    metadata:
      labels:
        chapter: sdev372
    spec:
      containers:
        - name: saas-container
          image: joshuanak/saas-project
          ports:
            - containerPort: 8080